[features]
seeds = true
skip-lint = false
[programs.devnet]
anchor_counter = "ALeaCzuJpZpoCgTxMjJbNjREVqSwuvYFRZUfc151AKHU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
